#!/usr/bin/env python3

import sys,csv,os
import argparse

from Bio import SeqIO
from Bio.Seq import Seq

parser = argparse.ArgumentParser()

parser.add_argument("--reference",
                    help="Reference sequence (fasta format)",
                    type=str,
                    required=True)

parser.add_argument("snps_file",
                    help="Output from show-snps(1)",
                    nargs='?',
                    type=argparse.FileType('r'),
                    default=sys.stdin)

arguments = parser.parse_args()

# This will need to be changed if the reference is a multi-fasta
sequence = SeqIO.read(arguments.reference,"fasta")
#vcf=open(sys.argv[2],'r')
reader = csv.reader(arguments.snps_file,delimiter='\t')
writer = csv.writer(sys.stdout,delimiter='\t')

for line in reader:
	if "#" in line[0]:
		continue
	position=int(line[1])
	alt=line[4]
	ref=line[3]
	# Insertions #
	if "." in line[3]:

		new_ref=sequence[position-1]
		line[3]=new_ref
		line[4]=new_ref+line[4]
		#line[4]=new_alt
	# Deletions
	if "." in line[4]:
		line[3]=sequence[position-2] + ref
		line[4]=sequence[position-2]

	writer.writerow(line)
