#!/usr/bin/env python2.7

import sys,csv,os
import argparse

from Bio import SeqIO
from Bio.Seq import Seq

parser = argparse.ArgumentParser()

parser.add_argument("--reference",
                    help="Reference sequence (fasta format)",
                    type=str,
                    required=True)

arguments = parser.parse_args()

fasta=open(arguments.reference,'r')
lines=fasta.readlines()
#vcf=open(sys.argv[2],'r')
output_file = open(sys.argv[3],'w')
with open(sys.argv[2],'r') as f:
	reader = csv.reader(f,delimiter='\t')
	writer = csv.writer(output_file,delimiter='\t')
	#fasta=fasta.strip('\n')
#	lines=lines.strip('\n')
	for line in lines:
		if ">" in line:
			j=''
			continue
		else:	
			j=j+line.strip('\n')		
			#j=line.strip('\n')
			sequence=Seq(j)
	for line in reader:
		if "#" in line[0]:
			continue
		position=int(line[1])
		alt=line[4]
		ref=line[3]
		# Insertions #
		if "." in line[3]:

			new_ref=sequence[position-1]
			line[3]=new_ref
			line[4]=new_ref+line[4]
			#line[4]=new_alt
		# Deletions
		if "." in line[4]:
			line[3]=sequence[position-2] + ref
			line[4]=sequence[position-2]

		writer.writerow(line)
