#!/usr/bin/env python3

import sys,csv,os
import argparse

from Bio import SeqIO
from Bio.Seq import Seq

parser = argparse.ArgumentParser()

parser.add_argument("--reference",
                    help="Reference sequence (fasta format)",
                    type=str,
                    required=True)

parser.add_argument("snps_file",
                    help="Output from show-snps(1)",
                    nargs='?',
                    type=argparse.FileType('r'),
                    default=sys.stdin)

arguments = parser.parse_args()

# This will need to be changed if the reference is a multi-fasta
sequence = SeqIO.read(arguments.reference,"fasta")
#vcf=open(sys.argv[2],'r')
reader = csv.reader(arguments.snps_file,delimiter='\t')
writer = csv.writer(sys.stdout,delimiter='\t')

for line in reader:
	if "#" in line[0]:
		continue
	position=int(line[0])
	alt=line[2]
	ref=line[1]
	# Insertions #
	if ref == ".":
		ref=sequence[position-1]
		alt=ref+alt
	# Deletions
	if alt == ".":
		ref=sequence[position-2] + ref
		alt=sequence[position-2]
	line[1] = ref
	line[2] = alt
	writer.writerow(line)
