#!/usr/bin/env python3

import sys,csv,os
import argparse
from enum import Enum

from Bio import SeqIO
from Bio.Seq import Seq


vcf_null = '.'

def write(writer, refid, position, ref, alt):
	writer.writerow([refid,
			 position,
			 vcf_null,
			 ref,
			 alt,
			 vcf_null,
			 'PASS',
			 vcf_null])

parser = argparse.ArgumentParser()

parser.add_argument("--reference",
                    help="Reference sequence (fasta format)",
                    type=str,
                    required=True)

parser.add_argument("snps_file",
                    help="Output from show-snps(1)",
                    nargs='?',
                    type=argparse.FileType('r'),
                    default=sys.stdin)

arguments = parser.parse_args()

seqs = {}
for seq in SeqIO.parse(arguments.reference,"fasta"):
	seqs[seq.id] = seq

reader = csv.reader(arguments.snps_file,delimiter='\t')
writer = csv.writer(sys.stdout,delimiter='\t',lineterminator='\n')

writer.writerow(['##fileformat=VCFv4.2'])
writer.writerow(['#CHROM','POS','ID','REF','ALT','QUAL','FILTER','INFO'])

var_type = Enum('var_type', 'snp insertion deletion')
last_var = None
ref, alt = '', ''

for line in reader:
	if "#" in line[0]:
		continue
	current_position=int(line[0])
	current_ref=line[1]
	current_alt=line[2]
	current_refid=line[10]
	# Insertions #
	if current_ref == ".":
		if last_var == var_type.insertion \
		   and position==current_position:
			alt += current_alt
			continue
		elif last_var:
			write(writer, refid, position, ref, alt)
		refid=current_refid
		ref=seqs[current_refid][current_position-1]
		alt=ref+current_alt
		position = current_position
		last_var = var_type.insertion
	# Deletions
	elif current_alt == ".":
		if last_var == var_type.deletion \
		   and current_position==(position + len(ref)):
			ref += current_ref
			continue
		elif last_var:
			write(writer, refid, position, ref, alt)
		refid=current_refid
		ref=seqs[current_refid][current_position-2] + current_ref
		alt=seqs[current_refid][current_position-2]
		position = current_position - 1
		last_var = var_type.deletion
	else:
		if last_var == var_type.snp \
		   and current_position==(position + len(ref)):
			ref += current_ref
			alt += current_alt
			continue
		elif last_var:
			write(writer, refid, position, ref, alt)
		last_var = var_type.snp
		refid=current_refid
		position = current_position
		ref=current_ref
		alt=current_alt

write(writer, refid, position, ref, alt)
