#!/usr/bin/env python3

import sys,csv,os
import argparse

from Bio import SeqIO
from Bio.Seq import Seq

parser = argparse.ArgumentParser()

parser.add_argument("--reference",
                    help="Reference sequence (fasta format)",
                    type=str,
                    required=True)

parser.add_argument("snps_file",
                    help="Output from show-snps(1)",
                    nargs='?',
                    type=argparse.FileType('r'),
                    default=sys.stdin)

arguments = parser.parse_args()

seqs = {}
for seq in SeqIO.parse(arguments.reference,"fasta"):
	seqs[seq.id] = seq

reader = csv.reader(arguments.snps_file,delimiter='\t')
writer = csv.writer(sys.stdout,delimiter='\t')

writer.writerow(['##fileformat=VCFv4.2'])
writer.writerow(['#CHROM','POS','ID','REF','ALT','QUAL','FILTER','INFO'])
vcf_null = '.'

for line in reader:
	if "#" in line[0]:
		continue
	position=int(line[0])
	alt=line[2]
	ref=line[1]
	refid=line[10]
	# Insertions #
	if ref == ".":
		ref=seqs[refid][position-1]
		alt=ref+alt
	# Deletions
	if alt == ".":
		ref=seqs[refid][position-2] + ref
		alt=seqs[refid][position-2]
		position = position - 1
	line[1] = ref
	line[2] = alt
	writer.writerow([refid,
                         position,
                         vcf_null,
                         ref,
                         alt,
                         vcf_null,
                         'PASS',
                         vcf_null])
